# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - name: Install dependencies
        run: npm i
      #- name: Format check
      #  run: npm run prettier:check --loglevel verbose
      #- name: Readme check
      #  run: npm run embedme:check
      - name: Devto
        env:
          DEV_TO_GIT_TOKEN: ${{ secrets.DEV_TO_GIT_TOKEN }}
        run: npm run dev-to-git
